[Features] Added orders, order items, and transactions entities
vianneynara/kuenyawz-api pull request #115
Opened 2024-11-17 15:47 UTC by ZeroFairy

resolved #102 

## Description
Added entitties:
- Orders
- Order Items
- Transactions

2024-11-17 16:08 UTC, vianneynara commented
Hmm kenapa masih fail ya

2024-11-18 01:54 UTC, vianneynara commented on src/main/java/dev/realtards/kuenyawz/entities/Account.java
> +
Set FetchType as EAGER

2024-11-18 02:11 UTC, vianneynara commented on src/main/java/dev/realtards/kuenyawz/entities/OrderItems.java
> +//@ToString(callSuper = true, exclude = "product")
Delete unused annotations

2024-11-18 02:11 UTC, vianneynara commented on src/main/java/dev/realtards/kuenyawz/entities/Orders.java
> +//@ToString(callSuper = true, exclude = "product")
Delete unused annotations

2024-11-18 02:11 UTC, vianneynara commented on src/main/java/dev/realtards/kuenyawz/entities/Transactions.java
> +//@ToString(callSuper = true, exclude = "product")
Delete unused annotations

2024-11-18 02:12 UTC, vianneynara commented on src/main/java/dev/realtards/kuenyawz/entities/Orders.java
> +    }
Enum and inner classes must be placed on the botto  of the file

2024-11-18 02:34 UTC, vianneynara commented on src/main/java/dev/realtards/kuenyawz/entities/Transactions.java
> +    }
PENDING EXPIRED SUCCESS CANCELLED

2024-11-18 02:55 UTC, vianneynara commented on src/main/java/dev/realtards/kuenyawz/entities/Orders.java
> +    }
WAITING_DOWN_PAYMENT("Waiting for down payment")
CONFIRMING("Waiting for confirmation from seller")
CONFIRMED("Confirmed by seller")
WAITING_SETTLEMENT"Waiting for settlement")
PROCESSING("Being processed")
DELIVERED("Order delivered")
CANCELLED("Order cancelled")

2024-11-18 02:55 UTC, vianneynara requested changes
Please

2024-11-18 03:30 UTC, vianneynara approved these changes

2024-11-18 03:30 UTC, vianneynara approved these changes

2024-11-18 03:34 UTC, vianneynara commented
all clear

2024-11-18 03:34 UTC, merged

2024-11-18 03:35 UTC, ZeroFairy commented
Thank you